# KEVIN SUNIL GEORGE - 19BTRCY016
LAB 6

# a.Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.

In [4]:
import numpy as  np
import pandas as pa
resident_details = {'name':['Amit','Saurav','Yatham','Kevin'] , 'age':[34 , 23 ,19 ,20]}
Flat_no = ['A2101','A2102','A2103','A2104']
df = pa.DataFrame(resident_details, index = Flat_no )
print(df)

         name  age
A2101    Amit   34
A2102  Saurav   23
A2103  Yatham   19
A2104   Kevin   20


# b.To create a 4X2 integer array and prints its attributes.

In [6]:
import numpy as  np
arr= [[2,4],[5,6],[6,7],[7,9]]
array1 = np.array(arr)
print(array1)

[[2 4]
 [5 6]
 [6 7]
 [7 9]]


# c.For the given numpy array return array of odd rows and even columns.

In [10]:
import numpy as  np
arr = [[12,34,53,22],[52,6,16,24],[55,69,72,13]]
array2 = np.array(arr)
array1 = array2[::2, 1::2]
print(array1)

[[34 22]
 [69 13]]


# d.To add the two NumPy arrays and modify a result array by calculating the square root of each element

In [7]:
import numpy as np
arr = [23,45,12,16]
arr1 = [32,45,11,33]
array1 = np.array(arr)
array2 =np.array(arr1)
array3 = (array1 + array2)
print(array3)
array4 = array3.astype(np.float)
for n in np.nditer(array4,op_flags = ['readwrite']):
    n[...] = n **(1/2) 
print(array4)

[55 90 23 49]
[7.41619849 9.48683298 4.79583152 7.        ]
